### PR TITLE
Make code compliant to strict mode.

### PR DESCRIPTION
**Pull request by yyjhao**
tap was also updated because the old one uses octal expressions which fails in strict mode.

### CODE REVIEW

**Comment by agnoster** [comment]
I think it'd be nice to have CI so that we automatically can see if PRs pass right in Github. I'll set up Travis.

**Comment by yyjhao** [comment]
Not sure if it's necessary for this repo given that there hasn't been much change. Also it was really easy and fast to run `npm test` locally.

**Comment by yyjhao** [comment]
Can you accept this PR before I merge it?

**Comment by agnoster** [comment]
Sorry, I just wanted to get travis set up first so that I can see the PR passing. I can definitely 👍 the changes you've made, so if you've run the tests locally that's good enough to merge.

**Comment by agnoster** [comment]
Merged master, which has the travis CI changes now. Hopefully we have to update this package rarely, but when we do it's nice to know the checks are automated.

**Comment by agnoster** [comment]
This did actually uncover some minor problems with the tests, which should now be fixed.

**Pull request merged**
